/* Generated by wbuild from "Neur.w"
** (generator version $Revision: 2.5 $ of $Date: 94/07/29 15:31:49 $)
*/
#ifndef _Neur_H_
#define _Neur_H_
#include <X11/Core.h>
#ifndef XtNneuralNetwork
#define XtNneuralNetwork "neuralNetwork"
#endif
#ifndef XtCNeuralNetwork
#define XtCNeuralNetwork "NeuralNetwork"
#endif
#ifndef XtRT_neural_network
#define XtRT_neural_network "T_neural_network"
#endif

#ifndef XtNneuronRadius
#define XtNneuronRadius "neuronRadius"
#endif
#ifndef XtCNeuronRadius
#define XtCNeuronRadius "NeuronRadius"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNmargin
#define XtNmargin "margin"
#endif
#ifndef XtCMargin
#define XtCMargin "Margin"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNhspace
#define XtNhspace "hspace"
#endif
#ifndef XtCHspace
#define XtCHspace "Hspace"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNvspace
#define XtNvspace "vspace"
#endif
#ifndef XtCVspace
#define XtCVspace "Vspace"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNforeground
#define XtNforeground "foreground"
#endif
#ifndef XtCForeground
#define XtCForeground "Foreground"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNneuronBackground
#define XtNneuronBackground "neuronBackground"
#endif
#ifndef XtCNeuronBackground
#define XtCNeuronBackground "NeuronBackground"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNpositiveLineColor
#define XtNpositiveLineColor "positiveLineColor"
#endif
#ifndef XtCPositiveLineColor
#define XtCPositiveLineColor "PositiveLineColor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNnegativeLineColor
#define XtNnegativeLineColor "negativeLineColor"
#endif
#ifndef XtCNegativeLineColor
#define XtCNegativeLineColor "NegativeLineColor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNlineFactor
#define XtNlineFactor "lineFactor"
#endif
#ifndef XtCLineFactor
#define XtCLineFactor "LineFactor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNdisplayLabels
#define XtNdisplayLabels "displayLabels"
#endif
#ifndef XtCDisplayLabels
#define XtCDisplayLabels "DisplayLabels"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNsignificantLinesWidth
#define XtNsignificantLinesWidth "significantLinesWidth"
#endif
#ifndef XtCSignificantLinesWidth
#define XtCSignificantLinesWidth "SignificantLinesWidth"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

typedef struct _NeurClassRec *NeurWidgetClass;
typedef struct _NeurRec *NeurWidget;
externalref WidgetClass neurWidgetClass;
#endif /*_Neur_H_*/
