/* Generated by wbuild from "Neur.w"
** (generator version $Revision: 2.5 $ of $Date: 94/07/29 15:31:49 $)
*/
#ifndef _NeurP_H_
#define _NeurP_H_
#include <X11/CoreP.h>
#include <X11/Neur.h>
typedef void  (*draw_neuron_Proc)(
#if NeedFunctionPrototypes
Widget,Position ,Position 
#endif
);
#define XtInherit_draw_neuron ((draw_neuron_Proc) _XtInherit)
typedef void  (*display_label_Proc)(
#if NeedFunctionPrototypes
Widget,unsigned  int ,unsigned  int ,unsigned  int 
#endif
);
#define XtInherit_display_label ((display_label_Proc) _XtInherit)
typedef void  (*display_line_Proc)(
#if NeedFunctionPrototypes
Widget,Region ,unsigned  int ,unsigned  int ,unsigned  int 
#endif
);
#define XtInherit_display_line ((display_line_Proc) _XtInherit)

typedef struct {
/* methods */
draw_neuron_Proc draw_neuron;
display_label_Proc display_label;
display_line_Proc display_line;
/* class variables */
} NeurClassPart;

typedef struct _NeurClassRec {
CoreClassPart core_class;
NeurClassPart neur_class;
} NeurClassRec;

typedef struct {
/* resources */
t_neural_network * neuralNetwork;
Dimension  neuronRadius;
Dimension  margin;
Dimension  hspace;
Dimension  vspace;
Pixel  foreground;
Pixel  neuronBackground;
Pixel  positiveLineColor;
Pixel  negativeLineColor;
Pixel  lineFactor;
Boolean  displayLabels;
int  significantLinesWidth;
/* private state */
GC  gc;
GC  neuron_background_gc;
GC  positive_line_gc;
GC  negative_line_gc;
XPoint ** points;
int  max_neurons;
} NeurPart;

typedef struct _NeurRec {
CorePart core;
NeurPart neur;
} NeurRec;

externalref NeurClassRec neurClassRec;

#endif /* _NeurP_H_ */
