/* Generated by wbuild from "Neur.w"
** (generator version $Revision: 2.5 $ of $Date: 94/07/29 15:31:49 $)
*/
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 4 "Neur.w"
#include "gen.h"
#include <X11/NeurP.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 29 "Neur.w"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 34 "Neur.w"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 69 "Neur.w"
static void resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 78 "Neur.w"
static void  draw_neuron(
#if NeedFunctionPrototypes
Widget,Position ,Position 
#endif
);
#line 86 "Neur.w"
static void  display_label(
#if NeedFunctionPrototypes
Widget,unsigned  int ,unsigned  int ,unsigned  int 
#endif
);
#line 107 "Neur.w"
static void  display_line(
#if NeedFunctionPrototypes
Widget,Region ,unsigned  int ,unsigned  int ,unsigned  int 
#endif
);
#line 150 "Neur.w"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);

static XtResource resources[] = {
#line 7 "Neur.w"
{XtNneuralNetwork,XtCNeuralNetwork,XtRT_neural_network,sizeof(((NeurRec*)NULL)->neur.neuralNetwork),XtOffsetOf(NeurRec,neur.neuralNetwork),XtRImmediate,(XtPointer)NULL },
#line 8 "Neur.w"
{XtNneuronRadius,XtCNeuronRadius,XtRDimension,sizeof(((NeurRec*)NULL)->neur.neuronRadius),XtOffsetOf(NeurRec,neur.neuronRadius),XtRImmediate,(XtPointer)3 },
#line 9 "Neur.w"
{XtNmargin,XtCMargin,XtRDimension,sizeof(((NeurRec*)NULL)->neur.margin),XtOffsetOf(NeurRec,neur.margin),XtRImmediate,(XtPointer)10 },
#line 10 "Neur.w"
{XtNhspace,XtCHspace,XtRDimension,sizeof(((NeurRec*)NULL)->neur.hspace),XtOffsetOf(NeurRec,neur.hspace),XtRImmediate,(XtPointer)300 },
#line 11 "Neur.w"
{XtNvspace,XtCVspace,XtRDimension,sizeof(((NeurRec*)NULL)->neur.vspace),XtOffsetOf(NeurRec,neur.vspace),XtRImmediate,(XtPointer)100 },
#line 12 "Neur.w"
{XtNforeground,XtCForeground,XtRPixel,sizeof(((NeurRec*)NULL)->neur.foreground),XtOffsetOf(NeurRec,neur.foreground),XtRString,(XtPointer)"black"},
#line 13 "Neur.w"
{XtNneuronBackground,XtCNeuronBackground,XtRPixel,sizeof(((NeurRec*)NULL)->neur.neuronBackground),XtOffsetOf(NeurRec,neur.neuronBackground),XtRString,(XtPointer)"gold"},
#line 14 "Neur.w"
{XtNpositiveLineColor,XtCPositiveLineColor,XtRPixel,sizeof(((NeurRec*)NULL)->neur.positiveLineColor),XtOffsetOf(NeurRec,neur.positiveLineColor),XtRString,(XtPointer)"blue"},
#line 15 "Neur.w"
{XtNnegativeLineColor,XtCNegativeLineColor,XtRPixel,sizeof(((NeurRec*)NULL)->neur.negativeLineColor),XtOffsetOf(NeurRec,neur.negativeLineColor),XtRString,(XtPointer)"red"},
#line 16 "Neur.w"
{XtNlineFactor,XtCLineFactor,XtRPixel,sizeof(((NeurRec*)NULL)->neur.lineFactor),XtOffsetOf(NeurRec,neur.lineFactor),XtRImmediate,(XtPointer)5 },
#line 17 "Neur.w"
{XtNdisplayLabels,XtCDisplayLabels,XtRBoolean,sizeof(((NeurRec*)NULL)->neur.displayLabels),XtOffsetOf(NeurRec,neur.displayLabels),XtRImmediate,(XtPointer)True },
#line 18 "Neur.w"
{XtNsignificantLinesWidth,XtCSignificantLinesWidth,XtRInt,sizeof(((NeurRec*)NULL)->neur.significantLinesWidth),XtOffsetOf(NeurRec,neur.significantLinesWidth),XtRImmediate,(XtPointer)0 },
};

NeurClassRec neurClassRec = {
{ /* core_class part */
(WidgetClass) &coreClassRec,
"Neur",
sizeof(NeurRec),
NULL,
_resolve_inheritance,
FALSE,
initialize,
NULL,
XtInheritRealize,
NULL,
0,
resources,
12,
NULLQUARK,
False ,
FALSE ,
False ,
False ,
destroy,
resize,
expose,
NULL,
NULL,
XtInheritSetValuesAlmost,
NULL,
XtInheritAcceptFocus,
XtVersion,
NULL,
NULL,
XtInheritQueryGeometry,
XtInheritDisplayAccelerator,
NULL 
},
{ /* Neur_class part */
draw_neuron,
display_label,
display_line,
},
};
WidgetClass neurWidgetClass = (WidgetClass) &neurClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  NeurWidgetClass c = (NeurWidgetClass) class;
  NeurWidgetClass super;
  if (class == neurWidgetClass) return;
  super = (NeurWidgetClass)class->core_class.superclass;
  if (c->neur_class.draw_neuron == XtInherit_draw_neuron)
    c->neur_class.draw_neuron = super->neur_class.draw_neuron;
  if (c->neur_class.display_label == XtInherit_display_label)
    c->neur_class.display_label = super->neur_class.display_label;
  if (c->neur_class.display_line == XtInherit_display_line)
    c->neur_class.display_line = super->neur_class.display_line;
}
#line 29 "Neur.w"
/*ARGSUSED*/static void destroy(self)Widget self;
{
  XtWarning("Not yet implemented");
}
#line 34 "Neur.w"
/*ARGSUSED*/static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
{
  XGCValues	xgcv;
  int		i;

  if (!((NeurWidget)self)->neur.neuralNetwork)
  {
    XtWarning("Need a neural network as a resource");
    exit(1);
  }
  ((NeurWidget)self)->neur.max_neurons = 0;
  for (i = 0;i < ((NeurWidget)self)->neur.neuralNetwork->num_layers;i++)
    ((NeurWidget)self)->neur.max_neurons = MY_MAX(((NeurWidget)self)->neur.neuralNetwork->layer_defs[i], ((NeurWidget)self)->neur.max_neurons);
  ((NeurWidget)self)->core.height = (((NeurWidget)self)->neur.neuronRadius * 2 + 2) * ((NeurWidget)self)->neur.max_neurons + 2 * ((NeurWidget)self)->neur.margin +
    ((NeurWidget)self)->neur.vspace * (((NeurWidget)self)->neur.max_neurons - 1); 
  ((NeurWidget)self)->core.width = (((NeurWidget)self)->neur.neuronRadius * 2 + 2) * (((NeurWidget)self)->neur.neuralNetwork->num_layers) + 
    (((NeurWidget)self)->neur.margin + ((NeurWidget)self)->neur.hspace) * (((NeurWidget)self)->neur.neuralNetwork->num_layers - 1);
  xgcv.foreground = ((NeurWidget)self)->neur.foreground;
  ((NeurWidget)self)->neur.gc = XCreateGC(XtDisplay(self), DefaultRootWindow(XtDisplay(self)),
		  GCForeground, &xgcv);
  xgcv.foreground = ((NeurWidget)self)->neur.positiveLineColor;
  ((NeurWidget)self)->neur.positive_line_gc = XCreateGC(XtDisplay(self), DefaultRootWindow(XtDisplay(self)),
				GCForeground, &xgcv);
  xgcv.foreground = ((NeurWidget)self)->neur.negativeLineColor;
  ((NeurWidget)self)->neur.negative_line_gc = XCreateGC(XtDisplay(self), DefaultRootWindow(XtDisplay(self)),
				GCForeground, &xgcv);
  xgcv.foreground = ((NeurWidget)self)->neur.neuronBackground;
  ((NeurWidget)self)->neur.neuron_background_gc = XCreateGC(XtDisplay(self), 
				    DefaultRootWindow(XtDisplay(self)),
				    GCForeground, &xgcv);
  ((NeurWidget)self)->neur.points = xmalloc(((NeurWidget)self)->neur.neuralNetwork->num_layers * sizeof (XPoint *));
  for (i = 0;i < ((NeurWidget)self)->neur.neuralNetwork->num_layers;i++)
    ((NeurWidget)self)->neur.points[i] = xmalloc(((NeurWidget)self)->neur.neuralNetwork->layer_defs[i] * sizeof (XPoint));
}
#line 69 "Neur.w"
/*ARGSUSED*/static void resize(self)Widget self;
{
  ((NeurWidget)self)->neur.vspace = (((NeurWidget)self)->core.height - (((NeurWidget)self)->neur.neuronRadius * 2 + 2) * ((NeurWidget)self)->neur.max_neurons + 2 * ((NeurWidget)self)->neur.margin) / 
    (((NeurWidget)self)->neur.max_neurons - 1); 
  ((NeurWidget)self)->neur.hspace =
    (((NeurWidget)self)->core.width - (((NeurWidget)self)->neur.neuronRadius * 2 + 2) * (((NeurWidget)self)->neur.neuralNetwork->num_layers)) / 
    (((NeurWidget)self)->neur.neuralNetwork->num_layers - 1) - ((NeurWidget)self)->neur.margin;
}
#line 78 "Neur.w"
/*ARGSUSED*/static void  draw_neuron(self,x,y)Widget self;Position  x;Position  y;
{
  XFillArc(XtDisplay(self), XtWindow(self), ((NeurWidget)self)->neur.neuron_background_gc,
	   x, y, ((NeurWidget)self)->neur.neuronRadius * 2, ((NeurWidget)self)->neur.neuronRadius * 2, 360 * 64, 360 * 64);
  XDrawArc(XtDisplay(self), XtWindow(self), ((NeurWidget)self)->neur.gc,
	   x, y, ((NeurWidget)self)->neur.neuronRadius * 2, ((NeurWidget)self)->neur.neuronRadius * 2, 360 * 64, 360 * 64);
}
#line 86 "Neur.w"
/*ARGSUSED*/static void  display_label(self,i,j,k)Widget self;unsigned  int  i;unsigned  int  j;unsigned  int  k;
{
  char	buf[256];
  
  snprintf(buf, sizeof (buf), "%f", 
	   ((NeurWidget)self)->neur.neuralNetwork->layers[k]->neurons[i].weights[j]);
  buf[sizeof (buf) - 1] = 0;
  XDrawString(XtDisplay(self), XtWindow(self), ((NeurWidget)self)->neur.gc,
	      ((NeurWidget)self)->neur.points[k][i].x +
	      (((NeurWidget)self)->neur.points[k - 1][j].x + 
	       2 * ((NeurWidget)self)->neur.neuronRadius + 2 -
	       ((NeurWidget)self)->neur.points[k][i].x) / 2,
	      ((NeurWidget)self)->neur.points[k][i].y + 1 + ((NeurWidget)self)->neur.neuronRadius +
	      (((NeurWidget)self)->neur.points[k - 1][j].y + 1 + ((NeurWidget)self)->neur.neuronRadius -
	       ((NeurWidget)self)->neur.points[k][i].y + 1 + ((NeurWidget)self)->neur.neuronRadius) / 2,
	      buf, strlen(buf));
}
#line 107 "Neur.w"
/*ARGSUSED*/static void  display_line(self,region,i,j,k)Widget self;Region  region;unsigned  int  i;unsigned  int  j;unsigned  int  k;
{
  XGCValues	xgcv;
  GC		gc;
  Position	x1, y1, x2, y2;
  Dimension	width, height;
  
  /*printf("%d %d %d\n", i, j, k);*/
  if (((NeurWidget)self)->neur.neuralNetwork->layers[k]->neurons[i].weights[j] >= 0.0)
    gc = ((NeurWidget)self)->neur.positive_line_gc;
  else
    gc = ((NeurWidget)self)->neur.negative_line_gc;
  xgcv.line_width = 
    ABS(((NeurWidget)self)->neur.neuralNetwork->layers[k]->neurons[i].weights[j]) * 
    ((NeurWidget)self)->neur.lineFactor;
  if (xgcv.line_width >= ((NeurWidget)self)->neur.significantLinesWidth)
    {
      XChangeGC(XtDisplay(self), gc, GCLineWidth, &xgcv);
      x1 = MY_MIN(((NeurWidget)self)->neur.points[k][i].x, 
		  ((NeurWidget)self)->neur.points[k - 1][j].x + 2 * ((NeurWidget)self)->neur.neuronRadius + 2);
      y1 = MY_MIN(((NeurWidget)self)->neur.points[k][i].y + 1 + ((NeurWidget)self)->neur.neuronRadius,
		  ((NeurWidget)self)->neur.points[k - 1][j].y + 1 + ((NeurWidget)self)->neur.neuronRadius);
      x2 = MY_MAX(((NeurWidget)self)->neur.points[k][i].x,
		  ((NeurWidget)self)->neur.points[k - 1][j].x + 2 * ((NeurWidget)self)->neur.neuronRadius + 2);
      y2 = MY_MAX(((NeurWidget)self)->neur.points[k][i].y + 1 + ((NeurWidget)self)->neur.neuronRadius,
		  ((NeurWidget)self)->neur.points[k - 1][j].y + 1 + ((NeurWidget)self)->neur.neuronRadius);
      if (XRectInRegion(region, x1, y1, x2 - x1, y2 - y1))
	{
	  XDrawLine(XtDisplay(self), XtWindow(self), gc,
		    ((NeurWidget)self)->neur.points[k][i].x,
		    ((NeurWidget)self)->neur.points[k][i].y + 1 + ((NeurWidget)self)->neur.neuronRadius,
		    ((NeurWidget)self)->neur.points[k - 1][j].x + 2 * ((NeurWidget)self)->neur.neuronRadius + 2,
		    ((NeurWidget)self)->neur.points[k - 1][j].y + 1 + ((NeurWidget)self)->neur.neuronRadius);
	  if (((NeurWidget)self)->neur.displayLabels)
	    display_label(self, i, j, k);
	}
    }
}
#line 150 "Neur.w"
/*ARGSUSED*/static void expose(self,event,region)Widget self;XEvent * event;Region  region;
{
  Position	xoff, yoff;
  Dimension	layer_height;
  unsigned int	i, j, k;

  region = XCreateRegion();
  XtAddExposureToRegion(event, region);
  for (j = 0;j < ((NeurWidget)self)->neur.neuralNetwork->num_layers;j++)
    {
      layer_height = ((NeurWidget)self)->neur.neuralNetwork->layer_defs[j] * (2 * ((NeurWidget)self)->neur.neuronRadius + 2) + 
	(((NeurWidget)self)->neur.neuralNetwork->layer_defs[j] - 1) * ((NeurWidget)self)->neur.vspace;
      yoff = (((NeurWidget)self)->core.height - 2 * ((NeurWidget)self)->neur.margin - layer_height) / 2 + ((NeurWidget)self)->neur.margin;
      xoff = ((NeurWidget)self)->neur.margin + (((NeurWidget)self)->neur.neuronRadius * 2 + 2 + ((NeurWidget)self)->neur.hspace) * j;;
      for (i = 0;i < ((NeurWidget)self)->neur.neuralNetwork->layer_defs[j];i++)
	{
	  if (XRectInRegion(region, xoff,
			    yoff + i * ((((NeurWidget)self)->neur.neuronRadius * 2 + 2) + ((NeurWidget)self)->neur.vspace),
			    ((NeurWidget)self)->neur.neuronRadius * 2, ((NeurWidget)self)->neur.neuronRadius * 2))
	    draw_neuron(self, 
			xoff, yoff + i * ((((NeurWidget)self)->neur.neuronRadius * 2 + 2) + ((NeurWidget)self)->neur.vspace));
	  ((NeurWidget)self)->neur.points[j][i].x = xoff;
	  ((NeurWidget)self)->neur.points[j][i].y = yoff + i * ((((NeurWidget)self)->neur.neuronRadius * 2 + 2) + ((NeurWidget)self)->neur.vspace);
	}
    }
  for (k = 1;k < ((NeurWidget)self)->neur.neuralNetwork->num_layers;k++)
    {
      for (i = 0;i < ((NeurWidget)self)->neur.neuralNetwork->layer_defs[k];i++)
	{
	  for (j = 0;j < ((NeurWidget)self)->neur.neuralNetwork->layers[k]->num_weights;j++)
	    {
	      display_line(self, region, i, j, k);
	    }
	}
    }
  XDestroyRegion(region);   
}
